name: Generate GitHub Contribution Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate:
    name: Generate Snake Animation
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Generate contribution snake
        uses: Platane/snk@v3
        with:
          github_user_name: shivani-scm
          github_token: ${{ secrets.GITHUB_TOKEN }}
          outputs: |
            dist/github-contribution-grid-snake.svg?palette=github-light
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Publish snake to output branch
        uses: crazy-max/ghaction-github-pages@v5
        with:
          build_dir: dist
          target_branch: output
          keep_history: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
